<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-38Q9L5G" failures="1" tests="11" name="Admin Flow" time="20.588" errors="0" timestamp="2025-06-26T11:40:25 IST">
  <testcase classname="tests.AdminOrderFlowTest" name="createOrder" time="3.471"/>
  <testcase classname="tests.AdminOrderFlowTest" name="downloadcompleteOnTimeReportTest" time="1.695"/>
  <testcase classname="tests.AdminOrderFlowTest" name="downloadcompleteWithDelayReportTest" time="0.186"/>
  <testcase classname="tests.AdminOrderFlowTest" name="splitOrder" time="0.131"/>
  <testcase classname="tests.AdminOrderFlowTest" name="updateTAT" time="2.322"/>
  <testcase classname="tests.AdminOrderFlowTest" name="addAndAssignUsers" time="2.172"/>
  <testcase classname="tests.AdminOrderFlowTest" name="addRemarks" time="0.764"/>
  <testcase classname="tests.AdminOrderFlowTest" name="addAttachments" time="0.659"/>
  <testcase classname="tests.AdminOrderFlowTest" name="completeStages" time="3.438"/>
  <testcase classname="tests.AdminOrderFlowTest" name="verifyCompletion" time="0.279"/>
  <testcase classname="tests.AdminOrderFlowTest" name="updateUser" time="0.138">
    <failure type="java.lang.AssertionError" message="User update failed! expected [200] but found [403]">
      <![CDATA[java.lang.AssertionError: User update failed! expected [200] but found [403]
at tests.AdminOrderFlowTest.updateUser(AdminOrderFlowTest.java:226)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- updateUser -->
</testsuite> <!-- Admin Flow -->
